language: python

python:
    - "2.7"
    - "3.4"

env:
    - DB="sqlite://"
    - DB="postgresql+psycopg2://postgres@127.0.0.1/evesrp_test"
    - DB="postgresql+pg8000://postgres@127.0.0.1/evesrp_test"
    - DB="mysql+pymysql://root@127.0.0.1/evesrp_test"
    - DB="mysql+cymysql://root@127.0.0.1/evesrp_test"

matrix:
    include:
        - python: "2.7"
          env: DB="mysql+mysqldb://root@127.0.0.1/evesrp_test"
        - python: "3.3"
          env: DB="sqlite://"
        - python: "pypy"
          env: DB="sqlite://"
        - python: "pypy"
          env: DB="postgresql+pg8000://postgres@127.0.0.1/evesrp_test"
        - python: "pypy"
          env: DB="mysql+mysqldb://root@127.0.0.1/evesrp_test"
        - python: "pypy3"
          env: DB="sqlite://"
        - python: "pypy3"
          env: DB="postgresql+pg8000://postgres@127.0.0.1/evesrp_test"
        - python: "pypy3"
          env: DB="mysql+pymysql://root@127.0.0.1/evesrp_test"
    allow_failures:
        - python: "pypy"
        - python: "pypy3"
    fast_finish: true

install: make build-deps

before_script:
    - yes | sudo add-apt-repository ppa:ondrej/mysql-5.6
    - sudo apt-get update -q
    - sudo apt-get remove -y mysql-server mysql-client
    - sudo apt-get install -y mysql-5.6
    - psql -c 'CREATE DATABASE evesrp_test;' -U postgres
    - mysql -e 'CREATE DATABASE evesrp_test;'
    - make all

script: make test
