language: python

python:
    - "2.7"
    - "3.4"

env:
    - DB="sqlite://"
    - DB="postgresql+psycopg2://postgres@127.0.0.1/evesrp_test"
    - DB="postgresql+pg8000://postgres@127.0.0.1/evesrp_test"
    - DB="mysql+pymysql://root@127.0.0.1/evesrp_test"
    - DB="mysql+cymysql://root@127.0.0.1/evesrp_test"

matrix:
    include:
        - python: "2.7"
          env: DB="mysql+mysqldb://root@127.0.0.1/evesrp_test"
        - python: "3.3"
          env: DB="sqlite://"
        - python: "pypy"
          env: DB="sqlite://"
        - python: "pypy"
          env: DB="postgresql+pg8000://postgres@127.0.0.1/evesrp_test"
        - python: "pypy"
          env: DB="mysql+mysqldb://root@127.0.0.1/evesrp_test"
        - python: "pypy3"
          env: DB="sqlite://"
        - python: "pypy3"
          env: DB="postgresql+pg8000://postgres@127.0.0.1/evesrp_test"
        - python: "pypy3"
          env: DB="mysql+pymysql://root@127.0.0.1/evesrp_test"
    allow_failures:
        - python: "pypy"
        - python: "pypy3"
    fast_finish: true

install: make build-deps

before_script:
    # Yanked and modifierd from https://gist.github.com/drogus/6718448
    - "sudo apt-get remove mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5"
    - "sudo apt-get autoremove"
    - "sudo apt-get install libaio1"
    - "wget -O mysql-apt.deb http://dev.mysql.com/get/mysql-apt-config_0.2.1-1ubuntu12.04_all.deb"
    - "sudo dpkg -i mysql-apt.deb"
    - "sudo apt-get update -q"
    - "sudo apt-get -o Dpkg::Options::='--force-confold' install -y mysql-server mysql-common mysql-client"
    # some config values were changed since 5.5
    - "sudo sed -i'' 's/table_cache/table_open_cache/' /etc/mysql/my.cnf"
    - "sudo sed -i'' 's/log_slow_queries/slow_query_log/' /etc/mysql/my.cnf"
    - "sudo /etc/init.d/mysql.server start"
    - psql -c 'CREATE DATABASE evesrp_test;' -U postgres
    - mysql -e 'CREATE DATABASE evesrp_test;'
    - make all

script: make test
